# Generated by Django 4.1.13 on 2025-07-17 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_id', models.CharField(max_length=50)),
                ('mmsi', models.CharField(blank=True, max_length=9)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('course', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vessel_tracks',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
        migrations.CreateModel(
            name='UserPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('ais', 'AIS Behavior'), ('fishing', 'Fishing Detection'), ('kattegat', 'Kattegat Region')], max_length=50)),
                ('prediction_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('prediction_result', models.JSONField()),
                ('confidence', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vessel_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vesseltrack')),
            ],
            options={
                'db_table': 'user_predictions',
            },
        ),
        migrations.AddIndex(
            model_name='vesseltrack',
            index=models.Index(fields=['user', '-timestamp'], name='vessel_trac_user_id_ef2e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='vesseltrack',
            index=models.Index(fields=['mmsi'], name='vessel_trac_mmsi_9f4a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', '-session_start'], name='user_sessio_user_id_068b93_idx'),
        ),
        migrations.AddIndex(
            model_name='userprediction',
            index=models.Index(fields=['user', '-prediction_time'], name='user_predic_user_id_b945a9_idx'),
        ),
    ]
