
services:
  backend:
    build:
      context: .  # 👈 root project folder
      dockerfile: FastAPI_Backend/Dockerfile
    volumes:
      - ./FastAPI_Backend:/app
      - ./model:/app/model
      - ./geospatial:/app/geospatial
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload


  # docker-compose.yml  (frontend block only)
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app           # ⬅ your source code
      - frontend_node_modules:/app/node_modules   # ⬅ linux-only modules
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true

volumes:
  frontend_node_modules:        # declare the named volume

